global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: fdb-otel-exporter
    static_configs:
      - targets:
          - fdb-otel-exporter:9200
