[[simple_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_durable_version"
field_name = "DurableVersion"
description = "Storage server durable version"

[[simple_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_version"
field_name = "Version"
description = "Storage server version"

[[counter_total_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_bytes_input"
field_name = "BytesInput"
description = "Total input bytes on storage server"

[[counter_total_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_bytes_durable"
field_name = "BytesDurable"
description = "Total durable bytes on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_bytes_queried"
field_name = "BytesQueried"
description = "Rate of bytes queried per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_mutations"
field_name = "Mutations"
description = "Rate of mutations per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_mutation_bytes"
field_name = "MutationBytes"
description = "Mutation throughput in bytes per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_get_range_queries"
field_name = "GetRangeQueries"
description = "Range queries per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_get_value_queries"
field_name = "GetValueQueries"
description = "Value queries per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_get_key_queries"
field_name = "GetKeyQueries"
description = "Key queries per second on storage server"

[[counter_rate_gauge]]
trace_type = "ProxyMetrics"
gauge_name = "cp_txn_commit_in"
field_name = "TxnCommitIn"
description = "Transaction commits per second on commit proxy"

[[counter_rate_gauge]]
trace_type = "ProxyMetrics"
gauge_name = "cp_txn_conflicts"
field_name = "TxnConflicts"
description = "Transaction conflict rate on commit proxy"

[[counter_rate_gauge]]
trace_type = "GrvProxyMetrics"
gauge_name = "gp_txn_start_in"
field_name = "TxnStartIn"
description = "Rate of transactions attempting to start on GRV proxy"

[[counter_rate_gauge]]
trace_type = "GrvProxyMetrics"
gauge_name = "gp_grv_req_in"
field_name = "TxnRequestIn"
description = "Rate of GRV requests on GRV proxy"

[[simple_gauge]]
trace_type = "MovingData"
gauge_name = "dd_shards_in_flight"
field_name = "InFlight"
description = "Shards in flight, reported by data distributor"

[[simple_gauge]]
trace_type = "MovingData"
gauge_name = "dd_shards_in_queue"
field_name = "InQueue"
description = "Shards in DD queue, reported by data distributor"

[[simple_gauge]]
trace_type = "MovingData"
gauge_name = "dd_average_shard_size"
field_name = "AverageShardSize"
description = "Average shard size in bytes, reported by data distributor"

[[simple_gauge]]
trace_type = "RkUpdate"
gauge_name = "rk_tps_limit"
field_name = "TPSLimit"
description = "TPS limit enforced by ratekeeper"

[[simple_gauge]]
trace_type = "RkUpdate"
gauge_name = "rk_released_tps"
field_name = "ReleasedTPS"
description = "TPS released, reported by ratekeeper"

[[elapsed_rate_gauge]]
trace_type = "ProcessMetrics"
gauge_name = "process_cpu_util"
field_name = "CPUSeconds"
description = "Process CPU utilization as a ratio"

[[simple_gauge]]
trace_type = "DDTrackerStats"
gauge_name = "dd_total_kv_size"
field_name = "TotalSizeBytes"
description = "Total KV size, reported by data distributor"

[[counter_rate_gauge]]
trace_type = "TLogMetrics"
gauge_name = "tl_bytes_input"
field_name = "BytesInput"
description = "Input byte rate on the tlog"

[[counter_rate_gauge]]
trace_type = "TLogMetrics"
gauge_name = "tl_empty_peek_rate"
field_name = "EmptyPeeks"
description = "Rate of empty peek requests on the tlog"

[[counter_rate_gauge]]
trace_type = "TLogMetrics"
gauge_name = "tl_non_empty_peek_rate"
field_name = "NonEmptyPeeks"
description = "Rate of non-empty peek requests on the tlog"

[[simple_gauge]]
trace_type = "GRVLatencyMetrics"
gauge_name = "gp_p99_grv_latency"
field_name = "P99"
description = "P99 server-side GRV latency reported by GRV proxy"

[[simple_gauge]]
trace_type = "CommitLatencyMetrics"
gauge_name = "cp_p99_commit_latency"
field_name = "P99"
description = "P99 server-side commit latency reported by commit proxy"

[[simple_gauge]]
trace_type = "ReadLatencyMetrics"
gauge_name = "ss_p99_read_latency"
field_name = "P99"
description = "P99 server-side read latency reported by storage server"

[[counter_rate_gauge]]
trace_type = "MasterMetrics"
gauge_name = "ms_live_committed_version_reqs"
field_name = "GetLiveCommittedVersionRequests"
description = "Rate of live committed version requests, reported by master"

[[counter_rate_gauge]]
trace_type = "MasterMetrics"
gauge_name = "ms_commit_version_reqs"
field_name = "GetCommitVersionRequests"
description = "Rate of commit version requests, reported by master"

[[counter_rate_gauge]]
trace_type = "MasterMetrics"
gauge_name = "ms_report_live_committed_version_reqs"
field_name = "ReportLiveCommittedVersionRequests"
description = "Rate of live committed version report requests, reported by master"

[[counter_rate_gauge]]
trace_type = "ResolverMetrics"
gauge_name = "rv_txns_resolved"
field_name = "ResolvedTransactions"
description = "Rate of transactions resolved by resolver"

[[counter_rate_gauge]]
trace_type = "ResolverMetrics"
gauge_name = "rv_bytes_resolved"
field_name = "ResolvedBytes"
description = "Bytes resolved per second by resolver"

[[counter_rate_gauge]]
trace_type = "ResolverMetrics"
gauge_name = "rv_batches_resolved"
field_name = "ResolveBatchIn"
description = "Rate of batches sent to resolver"

[[histogram_percentile_gauge]]
group = "tLog"
op = "commit"
percentiles = [0.5, 0.99]
gauge_name = "tl_median_commit_latency"
description = "Median tlog commit latency"
