[[simple_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_durable_version"
field_name = "DurableVersion"
description = "Storage server durable version"

[[simple_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_version"
field_name = "Version"
description = "Storage server version"

[[counter_total_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_bytes_input"
field_name = "BytesInput"
description = "Total input bytes on storage server"

[[counter_total_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_bytes_durable"
field_name = "BytesDurable"
description = "Total durable bytes on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_bytes_queried"
field_name = "BytesQueried"
description = "Rate of bytes queried per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_mutations"
field_name = "Mutations"
description = "Rate of mutations per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_mutation_bytes"
field_name = "MutationBytes"
description = "Mutation throughput in bytes per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_get_range_queries"
field_name = "GetRangeQueries"
description = "Range queries per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_get_value_queries"
field_name = "GetValueQueries"
description = "Value queries per second on storage server"

[[counter_rate_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_get_key_queries"
field_name = "GetKeyQueries"
description = "Key queries per second on storage server"

[[counter_rate_gauge]]
trace_type = "ProxyMetrics"
gauge_name = "cp_txn_commit_in"
field_name = "TxnCommitIn"
description = "Transaction commits per second on commit proxy"

[[counter_rate_gauge]]
trace_type = "ProxyMetrics"
gauge_name = "cp_txn_conflicts"
field_name = "TxnConflicts"
description = "Transaction conflict rate on commit proxy"

[[counter_rate_gauge]]
trace_type = "ProxyMetrics"
gauge_name = "cp_mutations"
field_name = "Mutations"
description = "Mutation rate on commit proxy"

[[counter_rate_gauge]]
trace_type = "ProxyMetrics"
gauge_name = "cp_mutation_bytes"
field_name = "MutationBytes"
description = "Mutation bytes rate on commit proxy"

[[counter_rate_gauge]]
trace_type = "ProxyMetrics"
gauge_name = "cp_max_compute"
field_name = "MaxCompute"
description = "Maximum compute duration on commit proxy (us)"

[[counter_rate_gauge]]
trace_type = "GrvProxyMetrics"
gauge_name = "gp_txn_start_in"
field_name = "TxnStartIn"
description = "Rate of transactions attempting to start on GRV proxy"

[[counter_rate_gauge]]
trace_type = "GrvProxyMetrics"
gauge_name = "gp_grv_req_in"
field_name = "TxnRequestIn"
description = "Rate of GRV requests on GRV proxy"

[[simple_gauge]]
trace_type = "MovingData"
gauge_name = "dd_shards_in_flight"
field_name = "InFlight"
description = "Shards in flight, reported by data distributor"

[[simple_gauge]]
trace_type = "MovingData"
gauge_name = "dd_shards_in_queue"
field_name = "InQueue"
description = "Shards in DD queue, reported by data distributor"

[[simple_gauge]]
trace_type = "MovingData"
gauge_name = "dd_average_shard_size"
field_name = "AverageShardSize"
description = "Average shard size in bytes, reported by data distributor"

[[simple_gauge]]
trace_type = "RkUpdate"
gauge_name = "rk_tps_limit"
field_name = "TPSLimit"
description = "TPS limit enforced by ratekeeper"

[[simple_gauge]]
trace_type = "RkUpdate"
gauge_name = "rk_released_tps"
field_name = "ReleasedTPS"
description = "TPS released, reported by ratekeeper"

[[elapsed_rate_gauge]]
trace_type = "ProcessMetrics"
gauge_name = "process_cpu_util"
field_name = "CPUSeconds"
description = "Process CPU utilization as a ratio"

[[simple_gauge]]
trace_type = "DDTrackerStats"
gauge_name = "dd_total_kv_size"
field_name = "TotalSizeBytes"
description = "Total KV size, reported by data distributor"

[[counter_rate_gauge]]
trace_type = "TLogMetrics"
gauge_name = "tl_bytes_input"
field_name = "BytesInput"
description = "Input byte rate on the tlog"

[[counter_rate_gauge]]
trace_type = "TLogMetrics"
gauge_name = "tl_empty_peek_rate"
field_name = "EmptyPeeks"
description = "Rate of empty peek requests on the tlog"

[[counter_rate_gauge]]
trace_type = "TLogMetrics"
gauge_name = "tl_non_empty_peek_rate"
field_name = "NonEmptyPeeks"
description = "Rate of non-empty peek requests on the tlog"

[[simple_gauge]]
trace_type = "GRVLatencyMetrics"
gauge_name = "gp_p99_grv_latency"
field_name = "P99"
description = "P99 server-side GRV latency reported by GRV proxy"

[[simple_gauge]]
trace_type = "CommitLatencyMetrics"
gauge_name = "cp_p99_commit_latency"
field_name = "P99"
description = "P99 server-side commit latency reported by commit proxy"

[[simple_gauge]]
trace_type = "ReadLatencyMetrics"
gauge_name = "ss_p50_read_latency"
field_name = "Median"
description = "Median server-side read latency reported by storage server"

[[simple_gauge]]
trace_type = "ReadLatencyMetrics"
gauge_name = "ss_p99_read_latency"
field_name = "P99"
description = "P99 server-side read latency reported by storage server"

[[simple_gauge]]
trace_type = "ReadLatencyMetrics"
gauge_name = "ss_p999_read_latency"
field_name = "P99.9"
description = "P999 server-side read latency reported by storage server"

[[counter_rate_gauge]]
trace_type = "MasterMetrics"
gauge_name = "ms_live_committed_version_reqs"
field_name = "GetLiveCommittedVersionRequests"
description = "Rate of live committed version requests, reported by master"

[[counter_rate_gauge]]
trace_type = "MasterMetrics"
gauge_name = "ms_commit_version_reqs"
field_name = "GetCommitVersionRequests"
description = "Rate of commit version requests, reported by master"

[[counter_rate_gauge]]
trace_type = "MasterMetrics"
gauge_name = "ms_report_live_committed_version_reqs"
field_name = "ReportLiveCommittedVersionRequests"
description = "Rate of live committed version report requests, reported by master"

[[counter_rate_gauge]]
trace_type = "ResolverMetrics"
gauge_name = "rv_txns_resolved"
field_name = "ResolvedTransactions"
description = "Rate of transactions resolved by resolver"

[[counter_rate_gauge]]
trace_type = "ResolverMetrics"
gauge_name = "rv_bytes_resolved"
field_name = "ResolvedBytes"
description = "Bytes resolved per second by resolver"

[[counter_rate_gauge]]
trace_type = "ResolverMetrics"
gauge_name = "rv_batches_resolved"
field_name = "ResolveBatchIn"
description = "Rate of batches sent to resolver"

[[histogram_percentile_gauge]]
group = "tLog"
op = "commit"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "tl_commit_latency"
description = "TLog commit latency"

[[histogram_percentile_gauge]]
group = "tLog"
op = "QueueWait"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "tl_queue_wait_latency"
description = "TLog queue wait latency"

[[histogram_percentile_gauge]]
group = "tLog"
op = "TimeUntilDurable"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "tl_time_until_durable_latency"
description = "TLog time until durable latency"

[[histogram_percentile_gauge]]
group = "StorageServer"
op = "SSVersionLockLatency"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "ss_version_lock_latency"
description = "Storage server version lock latency"

[[histogram_percentile_gauge]]
group = "StorageServer"
op = "TLogMsgsPTreeUpdatesLatency"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "ss_tlog_msgs_ptree_updates_latency"
description = "Storage server TLogMsgs PTree updates latency"

[[histogram_percentile_gauge]]
group = "StorageServer"
op = "StorageUpdatesDurableLatency"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "ss_storage_updates_durable_latency"
description = "Storage server updates durable latency"

[[histogram_percentile_gauge]]
group = "StorageServer"
op = "StorageCommitLatency"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "ss_storage_commit_latency"
description = "Storage server commit latency"

[[histogram_percentile_gauge]]
group = "StorageServer"
op = "TLogCursorReadsLatency"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "ss_tlog_cursor_reads_latency"
description = "Storage server TLog cursor reads latency"

[[histogram_percentile_gauge]]
group = "StorageServer"
op = "SSDurableVersionUpdateLatency"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "ss_durable_version_update_latency"
description = "Storage server durable version update latency"

[[histogram_percentile_gauge]]
group = "StorageServer"
op = "FetchKeysPTreeUpdatesLatency"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "ss_fetch_keys_ptree_updates_latency"
description = "Storage server fetch keys PTree updates latency"

[[histogram_percentile_gauge]]
group = "StorageServer"
op = "FetchKeysBytesPerCommit"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "ss_fetch_keys_bytes_per_commit"
description = "Storage server fetch keys bytes per commit"


[[histogram_percentile_gauge]]
group = "StorageServer"
op = "EagerReadsLatency"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "ss_eager_reads_latency"
description = "Storage server eager reads latency"

[[histogram_percentile_gauge]]
group = "CommitProxy"
op = "ProcessingMutation"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "cp_processing_mutation_latency"
description = "Commit proxy processing mutation latency"

[[histogram_percentile_gauge]]
group = "CommitProxy"
op = "PostResolutionQueuing"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "cp_post_resolution_queuing_latency"
description = "Commit proxy post-resolution queuing latency"

[[histogram_percentile_gauge]]
group = "CommitProxy"
op = "GetCommitVersion"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "cp_get_commit_version_latency"
description = "Commit proxy get commit version latency"

[[histogram_percentile_gauge]]
group = "CommitProxy"
op = "ReplyCommit"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "cp_reply_commit_latency"
description = "Commit proxy reply commit latency"

[[histogram_percentile_gauge]]
group = "CommitProxy"
op = "Resolution"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "cp_resolution_latency"
description = "Commit proxy resolution latency"

[[histogram_percentile_gauge]]
group = "CommitProxy"
op = "TlogLogging"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "cp_tlog_logging_latency"
description = "Commit proxy TLog logging latency"

[[histogram_percentile_gauge]]
group = "GrvProxy"
op = "GrvConfirmEpochLive"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "gp_confirm_epoch_live_latency"
description = "GRV proxy ConfirmEpochLive latency"

[[histogram_percentile_gauge]]
group = "GrvProxy"
op = "GrvGetCommittedVersionRpc"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "gp_get_committed_version_rpc_latency"
description = "GRV proxy GetCommittedVersionRpc latency"

[[histogram_percentile_gauge]]
group = "Resolver"
op = "ComputeTime"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "rv_compute_time_latency"
description = "Resolver compute time latency"

[[histogram_percentile_gauge]]
group = "Resolver"
op = "Latency"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "rv_latency"
description = "Resolver overall latency"

[[histogram_percentile_gauge]]
group = "Resolver"
op = "QueueWait"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "rv_queue_wait_latency"
description = "Resolver queue wait latency"

[[histogram_percentile_gauge]]
group = "Resolver"
op = "QueueDepth"
percentiles = [0.5, 0.99, 0.999]
gauge_name = "rv_queue_depth"
description = "Resolver queue depth"

[[simple_gauge]]
trace_type = "AsyncFileKAIOReadLatency"
gauge_name = "process_p50_async_file_kaio_read_latency"
field_name = "Median"
description = "P50 latency for AsyncFileKAIO read operations"

[[simple_gauge]]
trace_type = "AsyncFileKAIOReadLatency"
gauge_name = "process_p99_async_file_kaio_read_latency"
field_name = "P99"
description = "P99 latency for AsyncFileKAIO read operations"

[[simple_gauge]]
trace_type = "AsyncFileKAIOReadLatency"
gauge_name = "process_p999_async_file_kaio_read_latency"
field_name = "P99.9"
description = "P999 latency for AsyncFileKAIO read operations"

[[simple_gauge]]
trace_type = "AsyncFileKAIOWriteLatency"
gauge_name = "process_p50_async_file_kaio_write_latency"
field_name = "Median"
description = "P50 latency for AsyncFileKAIO write operations"

[[simple_gauge]]
trace_type = "AsyncFileKAIOWriteLatency"
gauge_name = "process_p99_async_file_kaio_write_latency"
field_name = "P99"
description = "P99 latency for AsyncFileKAIO write operations"

[[simple_gauge]]
trace_type = "AsyncFileKAIOWriteLatency"
gauge_name = "process_p999_async_file_kaio_write_latency"
field_name = "P99.9"
description = "P999 latency for AsyncFileKAIO write operations"

[[simple_gauge]]
trace_type = "AsyncFileKAIOSyncLatency"
gauge_name = "process_p50_async_file_kaio_sync_latency"
field_name = "Median"
description = "P50 latency for AsyncFileKAIO sync operations"

[[simple_gauge]]
trace_type = "AsyncFileKAIOSyncLatency"
gauge_name = "process_p99_async_file_kaio_sync_latency"
field_name = "P99"
description = "P99 latency for AsyncFileKAIO sync operations"

[[simple_gauge]]
trace_type = "AsyncFileKAIOSyncLatency"
gauge_name = "process_p999_async_file_kaio_sync_latency"
field_name = "P99.9"
description = "P999 latency for AsyncFileKAIO sync operations"

[[counter_rate_gauge]]
trace_type = "ClusterControllerMetrics"
gauge_name = "cc_open_db_reqs"
field_name = "OpenDatabaseRequests"
description = "Rate of open database requests, reported by cluster controller"

[[counter_rate_gauge]]
trace_type = "ClusterControllerMetrics"
gauge_name = "cc_status_reqs"
field_name = "StatusRequests"
description = "Rate of status requests, reported by cluster controller"

[[simple_gauge]]
trace_type = "MasterRecoveryState"
gauge_name = "cc_recovery_state"
field_name = "StatusCode"
description = "Recovery state, reported by cluster controller"

[[simple_gauge]]
trace_type = "CommitBatchingWindowSize"
gauge_name = "cp_p50_commit_batching_window"
field_name = "Median"
description = "Median commit batching window size"

[[simple_gauge]]
trace_type = "CommitBatchingWindowSize"
gauge_name = "cp_p99_commit_batching_window"
field_name = "P99"
description = "P99 commit batching window size"

[[simple_gauge]]
trace_type = "CommitBatchingWindowSize"
gauge_name = "cp_p999_commit_batching_window"
field_name = "P99.9"
description = "P999 commit batching window size"

[[simple_gauge]]
trace_type = "CommitBatchingEmptyMessageRatio"
gauge_name = "cp_p50_commit_batching_empty_message_ratio"
field_name = "Median"
description = "Median commit batching window empty message ratio"

[[simple_gauge]]
trace_type = "CommitBatchingEmptyMessageRatio"
gauge_name = "cp_p99_commit_batching_empty_message_ratio"
field_name = "P99"
description = "P99 commit batching window empty message ratio"

[[simple_gauge]]
trace_type = "CommitBatchingEmptyMessageRatio"
gauge_name = "cp_p999_commit_batching_empty_message_ratio"
field_name = "P99.9"
description = "P999 commit batching window empty message ratio"

[[simple_gauge]]
trace_type = "UpdateLatencyMetrics"
gauge_name = "ss_p50_update_latency"
field_name = "Median"
description = "Median update latency on storage server"

[[simple_gauge]]
trace_type = "UpdateLatencyMetrics"
gauge_name = "ss_p99_update_latency"
field_name = "P99"
description = "P99 update latency on storage server"

[[simple_gauge]]
trace_type = "UpdateLatencyMetrics"
gauge_name = "ss_p999_update_latency"
field_name = "P99.9"
description = "P999 update latency on storage server"

[[simple_gauge]]
trace_type = "ReadVersionWaitMetrics"
gauge_name = "ss_p50_read_version_wait"
field_name = "Median"
description = "Median read version wait latency"

[[simple_gauge]]
trace_type = "ReadVersionWaitMetrics"
gauge_name = "ss_p99_read_version_wait"
field_name = "P99"
description = "P99 read version wait latency"

[[simple_gauge]]
trace_type = "ReadVersionWaitMetrics"
gauge_name = "ss_p999_read_version_wait"
field_name = "P99.9"
description = "P999 read version wait latency"

[[simple_gauge]]
trace_type = "ReadQueueWaitMetrics"
gauge_name = "ss_p50_read_queue_wait"
field_name = "Median"
description = "Median read queue wait latency"

[[simple_gauge]]
trace_type = "ReadQueueWaitMetrics"
gauge_name = "ss_p99_read_queue_wait"
field_name = "P99"
description = "P99 read queue wait latency"

[[simple_gauge]]
trace_type = "ReadQueueWaitMetrics"
gauge_name = "ss_p999_read_queue_wait"
field_name = "P99.9"
description = "P999 read queue wait latency"

[[simple_gauge]]
trace_type = "StorageMetrics"
gauge_name = "ss_query_queue_max"
field_name = "QueryQueueMax"
description = "Maximum query queue depth on storage server"
