{
 "title": "FDB Metrics",
 "tags": [ "otel" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Process Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "description": "Per-process CPU utilization",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_util{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Ratekeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ratekeeper Throttling",
     "type": "timeseries",
     "description": "Shows TPS limit and released TPS metrics from ratekeeper",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rk_released_tps{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "rk_tps_limit{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "TLog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "TLog Non-Empty Peek Rate",
     "type": "timeseries",
     "description": "Rate of non-empty peek requests on the tlog",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "tl_non_empty_peek_rate{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TLog Empty Peek Rate",
     "type": "timeseries",
     "description": "Rate of empty peek requests on the tlog",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "tl_empty_peek_rate{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TLog Bytes Input",
     "type": "timeseries",
     "description": "Input byte rate on the tlog",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "tl_bytes_input{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 TLog Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tl_commit_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 TLog Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tl_commit_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 TLog Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tl_commit_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 TLog Queue Wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tl_queue_wait_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 TLog Queue Wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tl_queue_wait_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 TLog Queue Wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tl_queue_wait_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 TLog Time Until Durable",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tl_time_until_durable_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 TLog Time Until Durable",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tl_time_until_durable_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 TLog Time Until Durable",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tl_time_until_durable_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Commit Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commit Proxy Commit Rate",
     "type": "timeseries",
     "description": "Transaction commits per second on commit proxy",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "cp_txn_commit_in{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Commit Proxy Transaction Conflicts",
     "type": "timeseries",
     "description": "Transaction conflict rate on commit proxy",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "cp_txn_conflicts{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Commit Latency",
     "type": "timeseries",
     "description": "P99 server-side commit latency reported by commit proxy",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_p99_commit_latency{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Commit Proxy ProcessingMutation Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_processing_mutation_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Commit Proxy ProcessingMutation Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_processing_mutation_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Commit Proxy ProcessingMutation Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_processing_mutation_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Commit Proxy Post-Resolution Queuing Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_post_resolution_queuing_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Commit Proxy Post-Resolution Queuing Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_post_resolution_queuing_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Commit Proxy Post-Resolution Queuing Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_post_resolution_queuing_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Commit Proxy GetCommitVersion Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_get_commit_version_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Commit Proxy GetCommitVersion Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_get_commit_version_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Commit Proxy GetCommitVersion Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_get_commit_version_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Commit Proxy ReplyCommit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_reply_commit_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Commit Proxy ReplyCommit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_reply_commit_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Commit Proxy ReplyCommit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_reply_commit_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Commit Proxy Resolution Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_resolution_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Commit Proxy Resolution Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_resolution_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Commit Proxy Resolution Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_resolution_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Commit Proxy Tlog Logging Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_tlog_logging_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Commit Proxy Tlog Logging Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_tlog_logging_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Commit Proxy Tlog Logging Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cp_tlog_logging_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GRV Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "GRV Transaction Start Rate",
     "type": "timeseries",
     "description": "Rate of transactions attempting to start on GRV proxy",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "gp_txn_start_in{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GRV Requests per Second",
     "type": "timeseries",
     "description": "Rate of GRV requests on GRV proxy",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "gp_grv_req_in{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 GRV Latency",
     "type": "timeseries",
     "description": "P99 server-side GRV latency reported by GRV proxy",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gp_p99_grv_latency{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 GRV ConfirmEpochLive Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 773 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gp_confirm_epoch_live_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 GRV ConfirmEpochLive Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 773 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gp_confirm_epoch_live_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 GRV ConfirmEpochLive Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 773 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gp_confirm_epoch_live_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 GRV GetCommittedVersionRpc Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 781 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gp_get_committed_version_rpc_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 GRV GetCommittedVersionRpc Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 781 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gp_get_committed_version_rpc_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 GRV GetCommittedVersionRpc Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 781 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gp_get_committed_version_rpc_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Server Get Range Queries",
     "type": "timeseries",
     "description": "Range queries per second on storage server",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 446 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "ss_get_range_queries{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Server Mutation Bytes",
     "type": "timeseries",
     "description": "Mutation throughput in bytes per second on storage server",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 446 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "ss_mutation_bytes{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Server Get Key Queries",
     "type": "timeseries",
     "description": "Key queries per second on storage server",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 446 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "ss_get_key_queries{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Server Bytes Queried Rate",
     "type": "timeseries",
     "description": "Bytes queried per second by storage server",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 454 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "ss_bytes_queried{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Server Get Value Queries",
     "type": "timeseries",
     "description": "Value queries per second on storage server",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 454 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "ss_get_value_queries{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Queue",
     "type": "timeseries",
     "description": "Number of non-durable bytes on each storage server",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 454 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(ss_bytes_input{job=\"fdb-otel-exporter\"} - ss_bytes_durable{job=\"fdb-otel-exporter\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Read Latency",
     "type": "timeseries",
     "description": "P99 server-side read latency reported by storage server",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 462 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_p99_read_latency{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Non-Durable Versions",
     "type": "timeseries",
     "description": "Number of non-durable versions by storage server (should be ~5M in healthy state)",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 462 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(ss_version{job=\"fdb-otel-exporter\"} - ss_durable_version{job=\"fdb-otel-exporter\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Server Mutation Rate",
     "type": "timeseries",
     "description": "Rate of mutations per second on storage server",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 462 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "ss_mutations{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Storage Server Version Lock Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 470 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_version_lock_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Storage Server Version Lock Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 470 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_version_lock_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Storage Server Version Lock Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 470 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_version_lock_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Storage Server TLog Msgs PTree Updates Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 478 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_tlog_msgs_ptree_updates_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Storage Server TLog Msgs PTree Updates Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 478 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_tlog_msgs_ptree_updates_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Storage Server TLog Msgs PTree Updates Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 478 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_tlog_msgs_ptree_updates_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Storage Server Storage Updates Durable Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 486 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_storage_updates_durable_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Storage Server Storage Updates Durable Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 486 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_storage_updates_durable_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Storage Server Storage Updates Durable Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 486 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_storage_updates_durable_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Storage Server Storage Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 494 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_storage_commit_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Storage Server Storage Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 494 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_storage_commit_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Storage Server Storage Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 494 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_storage_commit_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Storage Server TLog Cursor Reads Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 502 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_tlog_cursor_reads_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Storage Server TLog Cursor Reads Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 502 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_tlog_cursor_reads_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Storage Server TLog Cursor Reads Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 502 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_tlog_cursor_reads_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Storage Server SS Durable Version Update Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 510 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_durable_version_update_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Storage Server SS Durable Version Update Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 510 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_durable_version_update_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Storage Server SS Durable Version Update Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 510 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_durable_version_update_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Storage Server Fetch Keys PTree Updates Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 518 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_fetch_keys_ptree_updates_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Storage Server Fetch Keys PTree Updates Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 518 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_fetch_keys_ptree_updates_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Storage Server Fetch Keys PTree Updates Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 518 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_fetch_keys_ptree_updates_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Storage Server Eager Reads Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 526 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_eager_reads_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Storage Server Eager Reads Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 526 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_eager_reads_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Storage Server Eager Reads Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 526 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ss_eager_reads_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Storage Server Fetch Keys Bytes Per Commit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 534 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ss_fetch_keys_bytes_per_commit_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Storage Server Fetch Keys Bytes Per Commit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 534 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ss_fetch_keys_bytes_per_commit_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Storage Server Fetch Keys Bytes Per Commit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 534 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ss_fetch_keys_bytes_per_commit_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Moving Data",
     "type": "timeseries",
     "description": "Data (in bytes) currently being moved between storage servers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 799 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "dd_average_shard_size{job=\"fdb-otel-exporter\"} * (dd_shards_in_queue{job=\"fdb-otel-exporter\"} + dd_shards_in_flight{job=\"fdb-otel-exporter\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total KV Size",
     "type": "timeseries",
     "description": "Total KV size of the cluster, reported by data distributor",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 799 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "dd_total_kv_size{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live Committed Version Reports",
     "type": "timeseries",
     "description": "Rate of live committed version report requests, reported by master",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 808 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "ms_report_live_committed_version_reqs{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Live Committed Version Requests",
     "type": "timeseries",
     "description": "Rate of live committed version requests, reported by master",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 808 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "ms_live_committed_version_reqs{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Commit Version Requests",
     "type": "timeseries",
     "description": "Rate of commit version requests, reported by master",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 808 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "ms_commit_version_reqs{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resolver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Resolved",
     "type": "timeseries",
     "description": "Bytes resolved per second by resolver",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rv_bytes_resolved{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resolved Transactions",
     "type": "timeseries",
     "description": "Rate of transactions resolved by resolver",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rv_txns_resolved{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resolved Batches",
     "type": "timeseries",
     "description": "Rate of batches sent to resolver",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rv_batches_resolved{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Resolver Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rv_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Resolver Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rv_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Resolver Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rv_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Resolver Compute Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rv_compute_time_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Resolver Compute Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rv_compute_time_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Resolver Compute Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rv_compute_time_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Resolver Queue Wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rv_queue_wait_latency_p50{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P99 Resolver Queue Wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rv_queue_wait_latency_p99{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P999 Resolver Queue Wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rv_queue_wait_latency_p99_9{job=\"fdb-otel-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}