name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fdb-otel-exporter
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt,llvm-tools-preview

      - name: Cache cargo build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Verify formatting
        run: cargo fmt --all --check

      - name: Lint with clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests
        run: cargo test --all --locked

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Generate coverage report
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info --html --output-dir coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: fdb-otel-exporter/lcov.info

      - name: Upload coverage pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: fdb-otel-exporter/coverage

  deploy-pages:
    needs: rust
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
